package ClientServer;

public enum CommandType {
    AUTH,
    AUTH_OK,
    ERROR,
    END,
    CREATE_NEW_USER,
    CONFIRMATION,
    UPDATE_USER,
    REQUEST_DIR, REQUEST_DIR_OK, FILE_SEND_REQEST, REQUEST_TRANSMITTER_OK, FILE_RECIVE_REQEST, REQUEST_RECIVE_OK;

}
