package ClientServer;

public enum CommandType {
    AUTH,
    AUTH_OK,
    ERROR,
    END,
    CREATE_NEW_USER,
    CONFIRMATION,
    UPDATE_USER,
    REQUEST_DIR,
    REQUEST_DIR_OK,
    FILE_UPLOAD_REQEST,
    REQUEST_TRANSMITTER_OK,
    FILE_DOWNLOAD_REQEST,
    REQUEST_DOWNLOAD_OK,
    CLOSE_CONNECTION,
    FILE_DATA
}
